name: BUILD

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 */1 * *"
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    name: Build Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Assets
        run: |
          python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: |
          set -x
          assets=()
          assets+=("./model.onnx")
          assets+=("./model.pickle")
          assets+=("./correlation.png")
          assets+=("./describe.json")
          assets+=("./modelEvaluation.json")
          tag_name=`date '+%Y%m%d%H%M'`
          gh release create "$tag_name" "${assets[@]}" -t "Latest"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 覚書
      # https://blog.3qe.us/entry/2020/02/17/164535
      - name: Commit
        run: |
            echo `date +%Y%m%d%H%M%S` > version.txt
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Auto Commit

      - name: Cleanup
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}