name: BUILD

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 */1 * *"
  workflow_dispatch:

jobs:
  build:
    name: Build Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6.5.0
      
      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Generate Assets
        run: |
          uv run main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: |
          set -x
          assets=()
          assets+=("./model.onnx")
          assets+=("./model.pickle")
          assets+=("./correlation.png")
          assets+=("./describe.json")
          assets+=("./modelEvaluation.json")
          tag_name=`date '+%Y%m%d%H%M'`
          gh release create "$tag_name" "${assets[@]}" -t "Latest"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Auto Commit

      - name: Cleanup
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}